### ISSUE TITLE
Failed to compile with Qt-5.3.2 on OS X

### ISSUE THREAD

**Issue by ghost** [ricardoquesada/cocos2d-console-gui#1]
```
In file included from ../../cocos2d-console-gui/src/main.cpp:17:
../../cocos2d-console-gui/src/mainwindow.h:40:5: error: 'metaObject' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:154:32: note: expanded from macro 'Q_OBJECT'
    virtual const QMetaObject *metaObject() const; \
                               ^
/usr/local/Qt-5.3.2/include/QtWidgets/qmainwindow.h:62:5: note: overridden virtual function is here
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:154:32: note: expanded from macro 'Q_OBJECT'
    virtual const QMetaObject *metaObject() const; \
                               ^
In file included from ../../cocos2d-console-gui/src/main.cpp:17:
../../cocos2d-console-gui/src/mainwindow.h:40:5: error: 'qt_metacast' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:155:19: note: expanded from macro 'Q_OBJECT'
    virtual void *qt_metacast(const char *); \
                  ^
/usr/local/Qt-5.3.2/include/QtWidgets/qmainwindow.h:62:5: note: overridden virtual function is here
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:155:19: note: expanded from macro 'Q_OBJECT'
    virtual void *qt_metacast(const char *); \
                  ^
In file included from ../../cocos2d-console-gui/src/main.cpp:17:
../../cocos2d-console-gui/src/mainwindow.h:40:5: error: 'qt_metacall' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:157:17: note: expanded from macro 'Q_OBJECT'
    virtual int qt_metacall(QMetaObject::Call, int, void **); \
                ^
/usr/local/Qt-5.3.2/include/QtWidgets/qmainwindow.h:62:5: note: overridden virtual function is here
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:157:17: note: expanded from macro 'Q_OBJECT'
    virtual int qt_metacall(QMetaObject::Call, int, void **); \
                ^
In file included from ../../cocos2d-console-gui/src/main.cpp:27:
../../cocos2d-console-gui/src/cocos2dguiapplication.h:23:5: error: 'metaObject' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:154:32: note: expanded from macro 'Q_OBJECT'
    virtual const QMetaObject *metaObject() const; \
                               ^
/usr/local/Qt-5.3.2/include/QtWidgets/qapplication.h:78:5: note: overridden virtual function is here
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:154:32: note: expanded from macro 'Q_OBJECT'
    virtual const QMetaObject *metaObject() const; \
                               ^
In file included from ../../cocos2d-console-gui/src/main.cpp:27:
../../cocos2d-console-gui/src/cocos2dguiapplication.h:23:5: error: 'qt_metacast' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:155:19: note: expanded from macro 'Q_OBJECT'
    virtual void *qt_metacast(const char *); \
                  ^
/usr/local/Qt-5.3.2/include/QtWidgets/qapplication.h:78:5: note: overridden virtual function is here
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:155:19: note: expanded from macro 'Q_OBJECT'
    virtual void *qt_metacast(const char *); \
                  ^
In file included from ../../cocos2d-console-gui/src/main.cpp:27:
../../cocos2d-console-gui/src/cocos2dguiapplication.h:23:5: error: 'qt_metacall' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:157:17: note: expanded from macro 'Q_OBJECT'
    virtual int qt_metacall(QMetaObject::Call, int, void **); \
                ^
/usr/local/Qt-5.3.2/include/QtWidgets/qapplication.h:78:5: note: overridden virtual function is here
    Q_OBJECT
    ^
/usr/local/Qt-5.3.2/include/QtCore/qobjectdefs.h:157:17: note: expanded from macro 'Q_OBJECT'
    virtual int qt_metacall(QMetaObject::Call, int, void **); \
                ^
6 errors generated.
make[2]: *** [debug/main.o] Error 1
make[1]: *** [debug] Error 2
make: *** [sub-src-make_first-ordered] Error 2
14:07:26: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project cocos2d-console-gui (kit: Qt 5.3.2)
When executing step "Make"
```

**Comment by ricardoquesada** [comment]
can you try with Qt 5.5.1 ? thanks.

**Comment by ghost** [comment]
success with Qt 5.5.1
